# use true colorsset -g default-terminal "screen-256color"

# vi mode
setw -g mode-keys vi

###############
# STATUS LINE #
###############

# set -g status-style bg='#1d2021',fg='#ebdbb2'
# set -g status-left-style bg='#1d2021',fg='#ebdbb2'
# set -g status-right-style bg='#1d2021',fg='#ebdbb2'
# set -g window-status-current-style bg='#1d2021',fg='#fe8019'
# set -g window-status-style bg='#1d2021',fg='#ebdbb2'

# Tab separator and format
set -g window-status-separator ' '
set -g window-status-format         " #I: #W "
set -g window-status-current-format " #I: #W "

# Styles
# set -g window-status-style          "bg=#3c3836,fg=#a89984"
# set -g window-status-current-style  "bg=#fe8019,fg=#1d2021"
###############
#  HIGHLIGHT  #
###############

# set -g mode-style bg='#fe8019',fg='#ebdbb2'
# set -g mode-style bg=orange, fg=white

###################
#   KEYBINDINGS   #
###################

# Ctrl-n, Ctrl-p for next and previous windows
bind C-p previous-window
bind C-n next-window

# make next/previous window switching repeatable
bind -r p previous-window
bind -r n next-window

# rebind C-a as prefix
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# vertical split with |. New pane is in current path
unbind %
bind | split-window -h -c "#{pane_current_path}"

# horizontal split with -. New pane is in current path
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# new window opens in current path
bind c new-window -c "#{pane_current_path}"

# refresh config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# pane resize
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# auto-rename windows
set -g allow-rename on

# no delay on esc
set -sg escape-time 0

# allows mouse interaction
set -g mouse on

# vim mode for scroll
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# open lazygit in new window
bind-key g new-window -n lazygit, -c "#{pane_current_path}" "lazygit"

# settings for kitty
set -gq allow-passthrough on
set -g visual-activity off

###################
# 		PLUGINS 		#
###################

# tpm plugin manager
set -g @plugin 'tmux-plugins/tpm'

# list of plugins
# tmux navigator
set -g @plugin 'christoomey/vim-tmux-navigator'

# gruvbox

set -g @plugin "adibhanna/gruvbox-tmux"
set -g @gruvbox-theme dark # dark or light

run '~/.config/tmux/plugins/tpm/tpm'
