import = [
  "~/.config/alacritty/themes/themes/gruvbox_material.toml"
]

live_config_reload = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"

[env]
TERM = "xterm-256color"

[font]
size = 20

# [font.glyph_offset]
# y = 9

[font.normal]
family = "BlexMono Nerd Font"
# style = "Medium"
style = "SemiBold"

[font.italic]
family = "BlexMono Nerd Font"
style = "Text Italic"

# [font.offset]
# y = 16

[scrolling]

# auto_scroll = true
# history = 2000

[window]
decorations = "buttonless"
opacity = 0.999

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 5
y = 5
