import = [
  "~/.config/alacritty/themes/themes/gruvbox_material.toml",
]

live_config_reload = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "BlexMono Nerd Font"
# style = "SemiBold"
style = "Regular"

[font.italic]
family = "BlexMono Nerd Font"
style = "Text Italic"

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[scrolling]
# auto_scroll = true
# history = 2000

[window]
decorations = "buttonless"
opacity = 0.9999

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 5
y = 5
